import:
  xls:
    EMM Onderdelen.xlsx:
      - name: Onderdelen
        colRow: 11
        cols:
          - name: host
            value: emm
          - name: schema
            value: product
          - title: Artikelnr.
            name: keyname
          - title: Artikelnr.
            name: orderCode
          # - title: Omschrijving
          #   name: productTitle
          - title: Verkoopprijs
            name: catalogPrice
    EMM Prijslijst NL.xls:
      - name: EMM BASIS
        colRow: 16
        cols:
          - name: host
            value: emm
          - name: schema
            value: product
          - title: Art. nummer
            name: keyname
          - title: Art. nummer
            name: orderCode
          - title: Groep
            name: group
          - title: Catalogus pag.
            name: catalogPage
          - title: NL Product Omschrijving
            name: description
          - title: NL Verpakking/Bestelhoeveelheid
            name: packageQuantity
          - title: NL
            name: catalogPrice
          - title: Korting
            name: purchaseDiscount
          - title: Vanaf
            name: scaleDiscountStart
          - title: Staffelkorting
            name: scaleDiscount
          - title: NL prijs per
            name: packingUnit
          - title: EAN-code
            name: eanCode

 Rhiwa Prijslijst.xlsx:
       - name: Mirka schuurmaterialen
         colRow: 1
         cols:
          -name: host
            value: Rhiwa
          - title: Art. Nr
            name: orderCode
          - title: Omschrijving
            name: description
          - title: Korrel
            name:
          - title: VE_stuks
            name: packageQuantity
          - title: Mirka_nr
            name: keyname
          - title: Catalogusprijs
            name: catalogPrice
          - title: EAN
            name: eanCode
          - title: CBS/Intrastat
            name:

          - name: machines en gereedschappen
          colRow: 1
          cols:
          - name: host
            value: Rhiwa
          - title: Art. Nr
            name: orderCode
          - title: Omschrijving
            name: description
          - title: Mirka nr.
            name: keyname
          - title: Eenheid
            name: packageQuantity
          - title: Catalogusprijs
            name: catalogPrice
          - title: Art_groep
            name:
          - title: EAN
            name: eanCode
          - title: CBS
            name:

          - name: Mirka rollen & banden
          colRow: 1
          cols:
          - name: host
           value: Rhiwa
          - title: Art. Nr
            name: orderCode
          - title: Omschrijving
            name: description
          - title: Korrel
            name:
          - title: VE_stuks
            name: packageQuantity
          - title: Mirka_nr
            name: keyname
          - title: Catalogusprijs
            name: catalogPrice
          - title: Art_groep
            name:
          - title: EAN
            name: eanCode

          - name: Sundstrom adembescherming
          colRow: 1
          cols:
            - name: host
             value: Rhiwa
            - title: Art. Nr
              name: orderCode
            - title: Omschrijving
              name: description
            - title: Bruto €
              name: catalogPrice
            - title: Eenheid
              name: packageQuantity
            - title: Art_groep
              name: keyname
            - title: EAN
              name: eanCode

          - name: poets en reinigingsmaterialen
          colRow: 1
          cols:
            - name: host
             value: Rhiwa
             - title: Artikelnr
             name: orderCode
             - title: Omschrijving
             name: description
             - title: Inhoud
             name: packageQuantity
             - title: Catalogusprijs
             name: catalogPrice

          - name: Perslucht
          colRow: 1
          cols:
            - name: host
            value: Rhiwa
            - title: Artikelnr
            name: orderCode
            - title: Omschrijving
            name: description
            - title: VE_Stuks
            name: packageQuantity
            - title: Korrel
            name:
            - title: Origineel nr.
            name:
            - title: Catalogusprijs
            name: catalogPrice
            - title: Art_groep
            name: keyname
            - title: EAN
            name: eanCode

        -   name: Div non Paint
          colRow: 1
          cols:
            - name: host
            value: Rhiwa
            - title: Artikelnr
            name: orderCode
            - title: Omschrijving
            name: description
            - title: VE_Stuks
            name: packageQuantity
            - title: Catalogusprijs
            name: catalogPrice
            - title: Art_groep
            name: keyname
            - title: EAN
            name: eanCode

WSB - SATA Advies Verkoopprijslijst.xlsx:
        - name: SATA BJ 2021
         colRow: 4
         cols:
           -name: host
           value: WSB
           - title: WSB Artikel nummer
           name: orderCode
           - title: Omschrijving Engels
           name: description
           - title: Omschrijving Nederlands:
             name: description
           - title: EAN code
             name: eanCode
           - title: Land van Herkomst
            name:
            - title: Statistiek nummers
            name:
            - title: Net. Gewicht in KG
             name:
            - title: Bruto gewicht in KG
             name:
            - title: Lengte in MM
             name:
            - title: Breedte in MM
             name:
            - title: Hoogte in MM
             name:
            - title: Bruto Advies Verkoopprijs 2021
             name: catalogPrice

WSB - RUPES Bruto Advies Verkoopprijslijst.xlsx:
        - name: WSB - RUPES Prijslijst 2021
          colRow: 4
          cols:
            -name: host
            value: WSB
            - title: Art. nr. WSB
            name: orderCode
            - title: Artikelomschrijving Engels:
              name: description
            - title: Artikelomschrijving Nederlands
            name: description
            - title: Artikelomschrijving Frans
            name: description
            - title: PG
            name:
            - title: PG omschrijving
            name:
            - title: EAN Codes
            name: eanCode
            - title: Statistiek Codes
            name:
            - title: Land van herkomst
            name:
            - title: Gewicht
            name:
            - title: Breedte
            name:
            - title: Lengte
            name:
            - title: Hoogte
            name:
            - title: Adviesprijs 2021
            name: catalogPrice

Ani Prijzen netto.xlsx:
          - name: Cliente 40572 PROVING   - P2
            colRow: 2
            cols:
              -name: host
              value: Ani
              - title: Code
              name: orderCode
              - title: Article
              name: description
              -title: NET PRICE
              name:

Proving PRIJSLIJST CAP Automotive.xlsx:
          - name: Prijslijst
            colRow: 49
            cols:
              - name: host
              value: CAP
              - title: ARTIKELNUMMER
             name: orderCode
             - title: Verpakkingeenheid
             name: packageQuantity
             -title: OMSCHRIJVING
             name: description
             - title: Catalogusprijs
             name: catalogPrice
             - title: Korting
             name: purchaseDiscount
             - title: Proving Prijsafspraak 2021
             name:

AiroNL_Netto.xls:
  name: Seite 1
  colRow: 1
  cols:
    -name: host
    value: Airo
    - title: Art.-Nr.
    name: orderCode
    - title: Omschrijving
    name: description
    - title: omschrijving 2
    name: description
    - title: Omschrijving 3
    name: description
    - title: Omschrijving 4
    name: description
    - title: Inhoud
    name:
    - title: Gewicht
    name:
    - title: Verpakkingseenheid
    name: packingUnit
    - title: verzendeenheid
    name:
    - title: stuks op pallet
    name:
    - title: Netto Prijs
    name:

  name: Seite 2
    colRow: 1
    cols:
      -name: host
      value: Airo
      - title: Art.-Nr.
      name: orderCode
      - title: Omschrijving
      name: description
      - title: omschrijving 2
      name: description
      - title: Omschrijving 3
      name: description
      - title: Omschrijving 4
      name: description
      - title: Inhoud
      name:
      - title: Gewicht
      name:
      - title: Verpakkingseenheid
      name: packingUnit
      - title: verzendeenheid
      name:
      - title: stuks op pallet
      name:
      - title: Netto Prijs
      name:

    name: Seite 3
      colRow: 1
      cols:
        -name: host
        value: Airo
        - title: Art.-Nr.
        name: orderCode
        - title: Omschrijving
        name: description
        - title: omschrijving 2
        name: description
        - title: Omschrijving 3
        name: description
        - title: Omschrijving 4
        name: description
        - title: Inhoud
        name:
        - title: Gewicht
        name:
        - title: Verpakkingseenheid
        name: packingUnit
        - title: verzendeenheid
        name:
        - title: stuks op pallet
        name:
        - title: Netto Prijs
        name:

      name: Seite 4
       colRow: 1
       cols:
         -name: host
         value: Airo
         - title: Art.-Nr.
         name: orderCode
         - title: Omschrijving
         name: description
         - title: omschrijving 2
         name: description
         - title: Omschrijving 3
         name: description
         - title: Omschrijving 4
         name: description
         - title: Inhoud
         name:
         - title: Gewicht
         name:
         - title: Verpakkingseenheid
         name: packingUnit
         - title: verzendeenheid
         name:
         - title: stuks op pallet
         name:
         - title: Netto Prijs
         name:

      name: Seite 5
        colRow: 1
        cols:
          -name: host
          value: Airo
          - title: Art.-Nr.
          name: orderCode
          - title: Omschrijving
          name: description
          - title: omschrijving 2
          name: description
          - title: Omschrijving 3
          name: description
          - title: Omschrijving 4
          name: description
          - title: Inhoud
          name:
          - title: Gewicht
          name:
          - title: Verpakkingseenheid
          name: packingUnit
          - title: verzendeenheid
          name:
          - title: stuks op pallet
          name:
          - title: Netto Prijs
          name:

      name: Seite 6
        colRow: 1
        cols:
          -name: host
          value: Airo
          - title: Art.-Nr.
          name: orderCode
          - title: Omschrijving
          name: description
          - title: omschrijving 2
          name: description
          - title: Omschrijving 3
          name: description
          - title: Omschrijving 4
          name: description
          - title: Inhoud
          name:
          - title: Gewicht
          name:
          - title: Verpakkingseenheid
          name: packingUnit
          - title: verzendeenheid
          name:
          - title: stuks op pallet
          name:
          - title: Netto Prijs
          name:

      name: Seite 7
        colRow: 1
        cols:
          -name: host
          value: Airo
          - title: Art.-Nr.
          name: orderCode
          - title: Omschrijving
          name: description
          - title: omschrijving 2
          name: description
          - title: Omschrijving 3
          name: description
          - title: Omschrijving 4
          name: description
          - title: Inhoud
          name:
          - title: Gewicht
          name:
          - title: Verpakkingseenheid
          name: packingUnit
          - title: verzendeenheid
          name:
          - title: stuks op pallet
          name:
          - title: Netto Prijs
          name:

      name: Seite 8
       colRow: 1
       cols:
         -name: host
         value: Airo
         - title: Art.-Nr.
         name: orderCode
         - title: Omschrijving
         name: description
         - title: omschrijving 2
         name: description
         - title: Omschrijving 3
         name: description
         - title: Omschrijving 4
         name: description
         - title: Inhoud
         name:
         - title: Gewicht
         name:
         - title: Verpakkingseenheid
         name: packingUnit
         - title: verzendeenheid
         name:
         - title: Netto Prijs
         name:

Prijslijst Chemicar.xlsx:
  name: BPM_PRL_Export
   colRow: 1
   cols:
     -name: host
     value: Chemicar
     -title: Item Code
     name: orderCode
     -title: Price
     name: catalogPrice
     - title: Qty
     name: packageQuantity
     - title: Discount Perc
     name: purchaseDiscount
     title: New Price
     name:
     - title: Item Desc
     name: description
     - title: Catalogue Page Nr
     name: catalogPage
     - title: Sales Unit
     name: packingUnit
     - title: Outer Box Units
     name: packageQuantity
     - title: Pallet Unit
     name:
     - title: Barcode
     name:
     - title: HSCode
     name:
     - title: Net Weight
     name:
     - title: Module Description
     name:
     - title: ABCD
     name:
     - title: Customer Code
     name:
     - title: Customer Name
     name:

Dynabrade EURO Price List.xlsx:
  name: Feuil1
    colRow: 8
    cols:
      -name: host
      value: Metaaltechniek
      - title: ITEM
      name: orderCode
      - title: SO DESC1
      name: description
      - title: EAN CODE
      name: eanCode
      - title: EURO 2021
      name: catalogPrice

Prijslijst Endstra.xlsx:
  name: Brutoprijs 2021
    colRow: 1
    cols:
      name: host
      value: Endstra
      - title: Artikelnummer
      name: orderCode
      - title: Omschrijving
      name: description
      - title: Bruto prijs huidig
      name: catalogPrice
      -title: Eenheid
      name: packingUnit
      - title: V.E.
      name: packageQuantity
      - title: EAN code
      name: eanCode

gerko airo nederland april.xlsx:
  name: Blad1
    colRow: 2
    cols:
      name: host
      value: Endstra
      - title: code
      name: orderCode
      - title: omschrijving
      name: description
      - title: prijs
      name:

INP SMART - NL.inkoop.xlsx:
  name: Blad1
   colRow: 1
   cols:
     name: host
     value: INP
     - title: Art.nr.
     name: orderCode
     - title: Omschrijving
     name: description
     - title: Verpakking
     name: packingUnit
     - title: EURO
     name:

Iwata AI_Fahrzeuglackierung_Preisliste.xlsx:
  name: Fahrzeuglackierung
   colRow: 1
   cols:
     name: host
     value: Iwata
     - title: Art.-Nr.
     name: orderCode
     - title: Bezeichnung
     name: description
     - title: Stück je VE
     name: packageQuantity
     - title: Catalogusprijs
       name: catalogPrice

KEMTEX PRIJSLIJST.xlsx:
  name: PRIJSLIJST 2021
   colRow: 1
   cols:
     name: host
     value: Kemtex
     - title: Artikel
     name: orderCode
     - title: Code EAN
     name: eanCode
     - title: Omschrijving
     name: description
     - title: VERPAKKING
     name: packageQuantity
     - title: TARIEF 2021
     name: catalogPrice
     -title: Korting
     -name: Discount


3M AAD Prijslijst.xlsx:
  name: AAD Prijslijst
   colRow: 1
   cols:
     name: host
     value: Metalak
     - title: Partnr.
     name: orderCode
     - title: Productomschrijving
     name: description
     - title: prijs per 1 sept 2021
     name: catalogPrice
     - title: Verkoop-eenheid (VE)
     name: packageQuantity

PPG alle producten Prijslijst.xlsx:
  name: Sheet1
   colRow: 4
  cols:
    name: host
    Value: PPG
    - title: PPG Item CODE
    name: orderCode
    - title: PPG Item Description
    name: description
    - title: Bruto prijs per 1 okt
    name: catalogPrice
    - title: Adjustment Value (1)
    name: Discount

Motip-Baten prijslijst.xlsx:
  name: BNL 6
   colRow: 11
   cols:
     name: host
     value: Baten Trading Company
     - title: Artikel
     name: orderCode
     - title: EAN code
     name: eanCode
     - title: Omschrijving NL
     name: Description
     -title: Advies-Prijs excl.
     name: catalogPrice
     -title: VERPAKKING
     name: packageQuantity

SHI Bruto prijslijst non paint.xlsx:
  name: Compleet
  colRow: 6
  cols:
    name: host
    value: SHI
    - title: Bestel nummer
    name: orderCode
    - title: Omschrijving
    name: description
    - title: EAN
    name: eanCode
    -title: BE
    name: packageQuantity
    -title: Bruto prijs vanaf                 01-03-'21
    name: catalogPrice

Majestic.xlsx:
  name: per maat
  colRow: 1
  cols:
    name: host
    value: Majestic
    -title: Artikel
    name: orderCode
    -title: Omschrijving
    name: description
    -title: maat
    name: description
    -title: Verpakt Per
    name: packageQuantity
    -title: Prijs
    name: catalogPrice
